version: '3.7'

services:
  database:
    build: ./backend/virtuoso
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - virtuoso_data:/data

  dispatcher:
    build: ./backend/dispatcher
    ports:
      - "8000:80"

  resources:
    build: ./backend/resources

  migrations:
    build: ./backend/migrations


volumes:
  virtuoso_data:
