version: '3.7'

services:
  database:
    build: ./backend/virtuoso
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - virtuoso_data:/data

  dispatcher:
    build: ./backend/dispatcher
    ports:
      - "8000:80"

  resources:
    build: ./backend/resources

  migrations:
    build: ./backend/migrations

  aggregations:
    build: ./backend/aggregations 
    environment:
      - BATCH_SIZE=750  # Otherwise virtuoso will create pretty long SQL queries and keep retrying with a smaller batch size until it succeeds
    ports:
      - 8888:80

volumes:
  virtuoso_data:
