version: '3.7'

services:
  db:
    build: ./backend/virtuoso
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - virtuoso_data:/data

  dispatcher:
    build: ./backend/dispatcher
    ports:
      - "8000:80"
    links:
      - resources:resources

  resources:
    build: ./backend/resources
    links:
      - db:database

  migrations:
    build: ./backend/migrations
    links:
      - db:database
    environment:
      - BATCH_SIZE=750  # Otherwise virtuoso will create pretty long SQL queries and keep retrying with a smaller batch size until it succeeds


volumes:
  virtuoso_data:
