name: LYNX Docker deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push (resources)
        uses: docker/build-push-action@v3
        with:
          context: backend/resources
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/lynx-resources:latest

      - name: Build and push (migrations)
        uses: docker/build-push-action@v3
        with:
          context: backend/migrations
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/lynx-migrations:latest
